require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PageFilesController do

  # This should return the minimal set of attributes required to create a valid
  # PageFile. As you add validations to PageFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all page_files as @page_files" do
      page_file = PageFile.create! valid_attributes
      get :index
      assigns(:page_files).should eq([page_file])
    end
  end

  describe "GET show" do
    it "assigns the requested page_file as @page_file" do
      page_file = PageFile.create! valid_attributes
      get :show, :id => page_file.id
      assigns(:page_file).should eq(page_file)
    end
  end

  describe "GET new" do
    it "assigns a new page_file as @page_file" do
      get :new
      assigns(:page_file).should be_a_new(PageFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested page_file as @page_file" do
      page_file = PageFile.create! valid_attributes
      get :edit, :id => page_file.id
      assigns(:page_file).should eq(page_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PageFile" do
        expect {
          post :create, :page_file => valid_attributes
        }.to change(PageFile, :count).by(1)
      end

      it "assigns a newly created page_file as @page_file" do
        post :create, :page_file => valid_attributes
        assigns(:page_file).should be_a(PageFile)
        assigns(:page_file).should be_persisted
      end

      it "redirects to the created page_file" do
        post :create, :page_file => valid_attributes
        response.should redirect_to(PageFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved page_file as @page_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageFile.any_instance.stub(:save).and_return(false)
        post :create, :page_file => {}
        assigns(:page_file).should be_a_new(PageFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageFile.any_instance.stub(:save).and_return(false)
        post :create, :page_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested page_file" do
        page_file = PageFile.create! valid_attributes
        # Assuming there are no other page_files in the database, this
        # specifies that the PageFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PageFile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => page_file.id, :page_file => {'these' => 'params'}
      end

      it "assigns the requested page_file as @page_file" do
        page_file = PageFile.create! valid_attributes
        put :update, :id => page_file.id, :page_file => valid_attributes
        assigns(:page_file).should eq(page_file)
      end

      it "redirects to the page_file" do
        page_file = PageFile.create! valid_attributes
        put :update, :id => page_file.id, :page_file => valid_attributes
        response.should redirect_to(page_file)
      end
    end

    describe "with invalid params" do
      it "assigns the page_file as @page_file" do
        page_file = PageFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageFile.any_instance.stub(:save).and_return(false)
        put :update, :id => page_file.id, :page_file => {}
        assigns(:page_file).should eq(page_file)
      end

      it "re-renders the 'edit' template" do
        page_file = PageFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageFile.any_instance.stub(:save).and_return(false)
        put :update, :id => page_file.id, :page_file => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested page_file" do
      page_file = PageFile.create! valid_attributes
      expect {
        delete :destroy, :id => page_file.id
      }.to change(PageFile, :count).by(-1)
    end

    it "redirects to the page_files list" do
      page_file = PageFile.create! valid_attributes
      delete :destroy, :id => page_file.id
      response.should redirect_to(page_files_url)
    end
  end

end
