require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SiteFilesController do

  # This should return the minimal set of attributes required to create a valid
  # SiteFile. As you add validations to SiteFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    @site = stub_model(Site, :id => 1, :name => "MyString", :template => "MyText")

    { :path => '/foo/bar', :name => 'n.n.', :site_id => @site.id }
  end

  describe "GET show" do
    it "assigns the requested site_file as @site_file" do
      site_file = SiteFile.create! valid_attributes
      get :show, :id => site_file.id
      assigns(:site_file).should eq(site_file)
    end
  end

  describe "GET new" do
    it "assigns a new site_file as @site_file" do
      get :new
      assigns(:site_file).should be_a_new(SiteFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested site_file as @site_file" do
      site_file = SiteFile.create! valid_attributes
      get :edit, :id => site_file.id
      assigns(:site_file).should eq(site_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SiteFile" do
        expect {
          post :create, :site_file => valid_attributes
        }.to change(SiteFile, :count).by(1)
      end

      it "assigns a newly created site_file as @site_file" do
        post :create, :site_file => valid_attributes
        assigns(:site_file).should be_a(SiteFile)
        assigns(:site_file).should be_persisted
      end

      it "redirects to the created site_file" do
        post :create, :site_file => valid_attributes
        response.should redirect_to(site_url(valid_attributes[:site_id]))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved site_file as @site_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteFile.any_instance.stub(:save).and_return(false)
        post :create, :site_file => {}
        assigns(:site_file).should be_a_new(SiteFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteFile.any_instance.stub(:save).and_return(false)
        post :create, :site_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested site_file" do
        site_file = SiteFile.create! valid_attributes
        # Assuming there are no other site_files in the database, this
        # specifies that the SiteFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SiteFile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => site_file.id, :site_file => {'these' => 'params'}
      end

      it "assigns the requested site_file as @site_file" do
        site_file = SiteFile.create! valid_attributes
        put :update, :id => site_file.id, :site_file => valid_attributes
        assigns(:site_file).should eq(site_file)
      end

      it "redirects to the site_file" do
        site_file = SiteFile.create! valid_attributes
        put :update, :id => site_file.id, :site_file => valid_attributes
        response.should redirect_to(site_url(site_file.site_id))
      end
    end

    describe "with invalid params" do
      it "assigns the site_file as @site_file" do
        site_file = SiteFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteFile.any_instance.stub(:save).and_return(false)
        put :update, :id => site_file.id, :site_file => {}
        assigns(:site_file).should eq(site_file)
      end

      it "re-renders the 'edit' template" do
        site_file = SiteFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteFile.any_instance.stub(:save).and_return(false)
        put :update, :id => site_file.id, :site_file => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested site_file" do
      site_file = SiteFile.create! valid_attributes
      expect {
        delete :destroy, :id => site_file.id
      }.to change(SiteFile, :count).by(-1)
    end

    it "redirects to the site_files list" do
      site_file = SiteFile.create! valid_attributes
      delete :destroy, :id => site_file.id
      response.should redirect_to(site_url(site_file.site_id))
    end
  end

end
